#!/bin/bash -e

# set source directory based on command-line argument (if specified)
if [ -n "$1" ]
then
    SRCDIR=$1
else
    SRCDIR=../work
fi

# 32-bit indices, optimized install
./cleanup && SUNINDEXTYPE=32 ./configure $SRCDIR
make -j
