#!/bin/bash -e

# remove previous installations
\rm -rf ../install_* ../examples_*

# 64-bit indices, optimized install
./cleanup && SUNINDEXTYPE=64 SUNINSTALLPREFIX=$PWD/../install_opt SUNEXAMPLEPREFIX=$PWD/../examples_opt ./configure
make -j install

# 64-bit indices, debug install
./cleanup && SUNINDEXTYPE=64 SUNBUILDTYPE=DBG SUNINSTALLPREFIX=$PWD/../install_dbg SUNEXAMPLEPREFIX=$PWD/../examples_dbg ./configure
make -j install

# 32-bit indices, optimized install
./cleanup && SUNINDEXTYPE=32 SUNINSTALLPREFIX=$PWD/../install_opt_int32 SUNEXAMPLEPREFIX=$PWD/../examples_opt_int32 ./configure
make -j install

# 32-bit indices, debug install
./cleanup && SUNINDEXTYPE=32 SUNBUILDTYPE=DBG SUNINSTALLPREFIX=$PWD/../install_dbg_int32 SUNEXAMPLEPREFIX=$PWD/../examples_dbg_int32 ./configure
make -j install
