#!/bin/bash

# clean up any previous build
./cleanup

# set source directory based on command-line argument (if specified)
if [ -n "$1" ]
then
    SRCDIR=$1
else
    SRCDIR=../develop
fi
echo "Configuring SUNDIALS from source code in $SRCDIR"
echo "  "

# set some path shortcuts
MPIDIR=/usr/local/mpich-3.3/gnu
KLUDIR=/usr/local/suitesparse-5.2.0/gnu
BLASLIB="-L/usr/local/openblas-0.3.6/gnu/lib -lopenblas"
LPKLIB="-L/usr/local/openblas-0.3.6/gnu/lib -lopenblas"
HYPREDIR=/usr/local/hypre-2.16.0/gnu
PETSCDIR=/usr/local/petsc-3.11.3/gnu
SLUDIR=/usr/local/superlu-mt-3.1/gnu
SLULIB=-lsuperlu_mt

# configure like normal
cmake \
 -DCMAKE_INSTALL_PREFIX:PATH="$PWD/../install_opt_int32" \
 -DEXAMPLES_INSTALL_PATH:PATH="$PWD/../examples_opt_int32" \
 -DCMAKE_C_COMPILER=$MPIDIR/bin/mpicc \
 -DMPI_C_COMPILER=$MPIDIR/bin/mpicc \
 -DCMAKE_Fortran_COMPILER=$MPIDIR/bin/mpif90 \
 -DMPI_Fortran_COMPILER=$MPIDIR/bin/mpif90 \
 -DCMAKE_CXX_COMPILER=$MPIDIR/bin/mpicxx \
 -DMPI_CXX_COMPILER=$MPIDIR/bin/mpicxx \
 -DMPIEXEC_EXECUTABLE=$MPIDIR/bin/mpiexec \
 -DCMAKE_MACOSX_RPATH=ON \
 -DCMAKE_C_FLAGS:STRING="-O3 -fPIC" \
 -DCMAKE_Fortran_FLAGS:STRING="-O3 -fPIC" \
 -DCMAKE_CXX_FLAGS:STRING="-O3 -fPIC" \
 -DOpenMP_C_FLAGS:STRING="-fopenmp" \
 -DOpenMP_CXX_FLAGS:STRING="-fopenmp" \
 -DSUNDIALS_PRECISION:STRING="double" \
 -DSUNDIALS_INDEX_SIZE:STRING="64" \
 -DEXAMPLES_ENABLE_C:BOOL="1" \
 -DEXAMPLES_ENABLE_CXX:BOOL="1" \
 -DEXAMPLES_ENABLE_F90:BOOL="1" \
 -DEXAMPLES_INSTALL:BOOL="1" \
 -DSUNDIALS_DEVTESTS=ON \
 -DF77_INTERFACE_ENABLE:BOOL="1" \
 -DF2003_INTERFACE_ENABLE:BOOL="1" \
 -DMPI_ENABLE:BOOL="1" \
 -DOPENMP_ENABLE:BOOL="1" \
 -DPTHREAD_ENABLE:BOOL="1" \
 -DBUILD_SHARED_LIBS:BOOL="1" \
 -DKLU_ENABLE:BOOL="1" \
 -DKLU_INCLUDE_DIR:STRING="$KLUDIR/include" \
 -DKLU_LIBRARY_DIR:FILEPATH="$KLUDIR/lib" \
 -DBLAS_ENABLE:BOOL="1" \
 -DBLAS_LIBRARIES:STRING="$BLASLIB" \
 -DLAPACK_ENABLE:BOOL="1" \
 -DLAPACK_LIBRARIES:STRING="$LPKLIB" \
 -DHYPRE_ENABLE:BOOL="1" \
 -DHYPRE_INCLUDE_DIR:STRING="$HYPREDIR/include" \
 -DHYPRE_LIBRARY_DIR:FILEPATH="$HYPREDIR/lib" \
 -DPETSC_ENABLE:BOOL="1" \
 -DPETSC_INCLUDE_DIR:STRING="$PETSCDIR/include" \
 -DPETSC_LIBRARY_DIR:FILEPATH="$PETSCDIR/lib" \
 $SRCDIR

# # to re-enable SuperLU_MT, add these above
# -DSUPERLUMT_ENABLE:BOOL="1" \
# -DSUPERLUMT_THREAD_TYPE:STRING="Pthread" \
# -DSUPERLUMT_INCLUDE_DIR:PATH="$SLUDIR/include" \
# -DSUPERLUMT_LIBRARY_DIR:FILEPATH="$SLUDIR/lib" \
# -DSUPERLUMT_LIBRARY:FILEPATH="-L$SLUDIR/lib $SLULIB $BLASLIB" \

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PETSCDIR/lib
