#!/bin/bash
#
# This uses a pre-configured build setup, so things like SUNREALTYPE, SUNINDEXTYPE, and the choice of various TPLs cannot be modified.
#
# The asymptote-config.txt file was generated using the following steps:
# 1. Configure the build interactively using either cmake-gui or ccmake,
#    for source files in $SRCDIR.
# 2. Run the following command:
#       cmake -N -LA $SRCDIR | tail -n+2 | sed -r 's/([A-Za-z_0-9]+):([A-Z]+)=(.*)/set(\1 "\3" CACHE \2 "")/' >asymptote-config.txt
#
# D. Reynolds
# 1/11/2024

# clean from any previous build
./cleanup

# set source directory based on command-line argument (if specified)
if [ -n "$1" ]
then
    SRCDIR=$1
else
    SRCDIR=../develop
fi
echo "  "
echo "Configuring SUNDIALS from source code in $SRCDIR"
echo "  "

cmake -C ./asymptote-config.txt $SRCDIR
